package com.github.mlposey;

/**
 * <p>An error generated by a {@link Translator}.</p>
 *
 * Translator provides methods for either ignoring or processing errors
 * of this type.
 */
public class TranslationError extends Error {
    private int code;

    /**
     * Creates a TranslationError object.
     *
     * @param code the response code generated by the translation service
     */
    public TranslationError(int code) { this.code = code; }

    /** Returns the response code generated by the translation service. */
    public int getCode() { return code; }
}
